version: '3'
services:
  ### NSQ settings
  nsqlookupd:
    image: nsqio/nsq
    container_name: twitter-votes-nsqlookupd
    hostname: twitter-votes-nsqlookupd
    command: /nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161
    networks:
      - twitter-votes
  nsqd:
    image: nsqio/nsq
    container_name: twitter-votes-nsqd
    hostname: twitter-votes-nsqd
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151
    networks:
      -  twitter-votes
  nsqadmin:
    image: nsqio/nsq
    container_name: twitter-votes-nsqd_admin
    hostname: twitter-votes-nsqd_admin
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - 4171:4171
    networks:
      -  twitter-votes
  ### MongoDB settings
  mongodb:
    image: mongo
    container_name: twitter-votes-mongodb
    hostname: twitter-votes-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    networks:
      -  twitter-votes
    volumes:
      - ~/workspace/twitter-votes/db:/data/db
      - ~/workspace/twitter-votes/configdb:/data/configdb

### Network settings
networks:
  twitter-votes:
    external: true
